#!/bin/bash
# List all available smoke tests

echo "📋 Available Smoke Tests"
echo "========================"
echo ""
echo "Phase 1: Backend Verification"
echo "  • 1.1 - Health Check Validation"
echo "  • 1.2 - AudioService Initialization"
echo "  • 1.3 - Deepgram API Connection"
echo ""
echo "Phase 2: Socket.IO Audio Streaming"
echo "  • 2.1 - Socket Connection"
echo "  • 2.2 - Audio Stream Upload"
echo "  • 2.3 - Speech-to-Text Processing"
echo ""
echo "Phase 3: Error Handling"
echo "  • 3.1 - Invalid Audio Format"
echo "  • 3.2 - Deepgram API Failure Handling"
echo "  • 3.3 - Network Interruption Recovery"
echo "  • 3.4 - Multiple Rapid Connections"
echo "  • 3.5 - Stream Without Starting"
echo ""
echo "Sentry Integration"
echo "  • Captures intentional errors via debug endpoint"
echo "  • Server remains healthy after Sentry error"
echo "  • Health check does not trigger Sentry errors"
echo "  • Sentry configuration is present"
echo "  • Multiple errors are handled independently"
echo ""
echo "📝 Total: 17 tests across 4 test suites"
echo ""
echo "To run all tests:    npm run test:smoke"
echo "To run Phase 1 only: npm run test:phase1"
echo "To run Phase 2 only: npm run test:phase2"
echo "To run Phase 3 only: npm run test:phase3"
echo ""
echo "Or use the automated script: ./scripts/run-smoke-tests.sh"
